name: highest_lowest
description: >-
  Extension methods for List<num>, List<int>, and List<double> that adds
  getters for returning the highest or lowest number in the list.
version: 0.1.0
homepage: https://github.com/james-alex/highest_lowest

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
